"""Idempotent DDL for the HELIOS OLTP source database (ADR-002).

The schema is applied by the seeder against a running instance — the compose
volume predates the schema and must never be rebuilt. Every SQL statement is
a single static string literal at its execution site (no concatenation, no
assembly, no interpolation — Mimosa source rule).
"""

from __future__ import annotations


def ensure_tables(conn) -> None:
    """CREATE TABLE IF NOT EXISTS for the four normalized tables (no constraints
    yet — those are added post-COPY by ensure_constraints for load speed)."""
    with conn.transaction():
        conn.execute("CREATE TABLE IF NOT EXISTS public.users (user_id BIGINT GENERATED BY DEFAULT AS IDENTITY, email TEXT NOT NULL, full_name TEXT NOT NULL, country_code TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, last_login_at TIMESTAMPTZ, is_active BOOLEAN NOT NULL DEFAULT TRUE)")
        conn.execute("CREATE TABLE IF NOT EXISTS public.orders (order_id BIGINT GENERATED BY DEFAULT AS IDENTITY, user_id BIGINT NOT NULL, status TEXT NOT NULL, currency TEXT NOT NULL, total_amount NUMERIC(12,2) NOT NULL, placed_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL)")
        conn.execute("CREATE TABLE IF NOT EXISTS public.order_items (order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY, order_id BIGINT NOT NULL, product_sku TEXT NOT NULL, quantity INTEGER NOT NULL, unit_price NUMERIC(10,2) NOT NULL)")
        conn.execute("CREATE TABLE IF NOT EXISTS public.payments (payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY, order_id BIGINT NOT NULL, method TEXT NOT NULL, amount NUMERIC(12,2) NOT NULL, status TEXT NOT NULL, paid_at TIMESTAMPTZ NOT NULL)")


def _constraint_exists(conn, name: str) -> bool:
    row = conn.execute("SELECT 1 FROM pg_constraint WHERE conname = %s LIMIT 1", (name,)).fetchone()
    return row is not None


def ensure_constraints(conn) -> None:
    """Add PK / UNIQUE / FK constraints if missing. Safe to run on every seed:
    after a crash between data load and constraint creation, the next run
    self-heals. FK validation scans the loaded data, so this is post-COPY."""
    with conn.transaction():
        if not _constraint_exists(conn, "pk_users"):
            conn.execute("ALTER TABLE public.users ADD CONSTRAINT pk_users PRIMARY KEY (user_id)")
        if not _constraint_exists(conn, "uq_users_email"):
            conn.execute("ALTER TABLE public.users ADD CONSTRAINT uq_users_email UNIQUE (email)")
        if not _constraint_exists(conn, "pk_orders"):
            conn.execute("ALTER TABLE public.orders ADD CONSTRAINT pk_orders PRIMARY KEY (order_id)")
        if not _constraint_exists(conn, "pk_order_items"):
            conn.execute("ALTER TABLE public.order_items ADD CONSTRAINT pk_order_items PRIMARY KEY (order_item_id)")
        if not _constraint_exists(conn, "pk_payments"):
            conn.execute("ALTER TABLE public.payments ADD CONSTRAINT pk_payments PRIMARY KEY (payment_id)")
        if not _constraint_exists(conn, "fk_orders_user_id"):
            conn.execute("ALTER TABLE public.orders ADD CONSTRAINT fk_orders_user_id FOREIGN KEY (user_id) REFERENCES public.users (user_id)")
        if not _constraint_exists(conn, "fk_order_items_order_id"):
            conn.execute("ALTER TABLE public.order_items ADD CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES public.orders (order_id) ON DELETE CASCADE")
        if not _constraint_exists(conn, "fk_payments_order_id"):
            conn.execute("ALTER TABLE public.payments ADD CONSTRAINT fk_payments_order_id FOREIGN KEY (order_id) REFERENCES public.orders (order_id) ON DELETE CASCADE")


def ensure_indexes(conn) -> None:
    """Secondary indexes for the query shapes the platform uses (mutator scans,
    Phase-2 watermark extraction by placed_at)."""
    with conn.transaction():
        conn.execute("CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders (user_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_orders_placed_at ON public.orders (placed_at)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders (status)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items (order_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_payments_order_id ON public.payments (order_id)")


def apply_schema(conn) -> None:
    """Full idempotent schema application (used by tests and as the seeder's
    building block)."""
    ensure_tables(conn)
    ensure_constraints(conn)
    ensure_indexes(conn)
